### PR TITLE
DLS-9912: [SDIL a11y] SDIL reference number validation message [WCAG/P1]

### PR DESCRIPTION
**Pull request by drewmiley**

### CODE REVIEW

**Comment by drewmiley** [comment]
Invalid SDIL ref
Screenshot 2024-01-30 at 14 59 16

**Comment by drewmiley** [comment]
More than 6 Letters
Screenshot 2024-01-30 at 14 59 26

**Comment by drewmiley** [comment]
Less than 9 Numbers
Screenshot 2024-01-30 at 14 59 45

**Review by GinnyThomas — APPROVED** [review]
Great work!  Really good way to break down the requirement further that allowed for easy integration into the tests.

**Pull request merged**
